### ISSUE TITLE
SQL Server connection and migrations

### ISSUE THREAD

**Issue by jongio** [jasontaylordev/azd-blazor#2]
Hi Jason, I tried your azd-blazor template, which looks nice, thanks for putting it together.

I'd like to see if you can get the SQL Server connection working when the app is deployed to Azure.

I believe you need to run migrations on it and you'll need to set the default connection here:

<img width="225" alt="image" src="https://github.com/jasontaylordev/azd-blazor/assets/2163001/3cbbefdb-591b-49d5-9074-4a2fcd1d782e">

Or put the connection string value in KV and update the app to read it from there.

A good test would be registering a new user via the identity interface of the app.  This is what you get today when you do so

<img width="504" alt="image" src="https://github.com/jasontaylordev/azd-blazor/assets/2163001/1de8d100-0200-4641-9b3b-8021b03ad309">

**Comment by jasontaylordev** [comment]
Thanks for your review and feedback @jongio. I've created a #3 to implement the requested changes. The application runs migrations at run time and will use the connection string stored in the key vault.
